name: All State Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape All States
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install scraper
        run: pip install warn-scraper

      - name: Scrape all states
        run: warn-scraper --data-dir ./data/

      - name: Upload all data
        uses: actions/upload-artifact@v4
        with:
          name: all-states
          path: ./data/
